let clubs = [
  {
    id: 1,
    name: "Ростов",
    logo: "rostov.png",
    ticket_shop: "https://tickets.fc-rostov.ru/",
    show: 1,
  },
  {
    id: 2,
    name: "ЦСКА",
    logo: "cska.png",
    ticket_shop: "https://events.pfc-cska.com/calendar",
    show: 1,
  },
  {
    id: 3,
    name: "Зенит",
    logo: "zenit.png",
    ticket_shop: "https://tickets.fc-zenit.ru/football/tickets/",
    show: 1,
  },
  {
    id: 4,
    name: "Спартак",
    logo: "spartak.png",
    ticket_shop: "https://tickets.spartak.com/",
    show: 1,

  },
  {
    id: 5,
    name: "Динамо",
    logo: "dynamo.png",
    ticket_shop: "https://fcdynamo.ru/shop/tickets/",
    show: 1,
  },
  {
    id: 6,
    name: "Локомотив",
    logo: "lokomotiv.png",
    ticket_shop: "https://tickets.fclm.ru/ru/",
    show: 1,
  },
  {
    id: 7,
    name: "Краснодар",
    logo: "krasnodar.png",
    ticket_shop: "https://www.fckrasnodar.ru/stadium/tickets",
    show: 1,
  },
  {
    id: 8,
    name: "Сборная",
    logo: "disabled.png",
    ticket_shop: "",
    show: 1,
  },
  {
    id: 9,
    name: "Химки",
    logo: "khimki.png",
    ticket_shop: "https://tickets.fckhimki.com/",
  },
  {
    id: 10,
    name: "Ротор",
    logo: "rotor.png",
    ticket_shop: "https://vlg.kassir.ru/bilety-na-sportivnye-meropriyatiya",
  },
  {
    id: 11,
    name: "Урал",
    logo: "ural.png",
    // ticket_shop: "",
  },
  {
    id: 12,
    name: "Сочи",
    logo: "sochi.png",
    ticket_shop: "https://tickets.pfcsochi.ru/",
  }, {
    id: 13,
    name: "Уфа",
    logo: "ufa.png",
    ticket_shop: "https://tickets.fcufa.pro/",
  }, {
    id: 14,
    name: "Ахмат",
    logo: "akhmat.png",
    ticket_shop: "https://www.ticketland.ru/persons/fk-terek/",
  }, {
    id: 15,
    name: "Тамбов",
    logo: "tambov.png",
    ticket_shop: "http://fc-tambov.ru/modules/content/page.php?id=4125",
  }, {
    id: 16,
    name: "Рубин",
    logo: "rubin.png",
    ticket_shop: "https://tickets.rubin-kazan.ru/",
  }, {
    id: 17,
    name: "Арсенал",
    logo: "arsenal.png",
    ticket_shop: "https://arsenaltula.ru/tickets/bilety_onlain/",
  },
];
let games = [
  {
    "round": "Round 20",
    "city": "Грозный",
    "date": "2021-02-28",
    "time": "16:30",
    "team1": "Ахмат",
    "team2": "Динамо",
    "iata1": "GRV",
    "iata2": "MOW",
    "img": "akhmat",
  },
  {
    "round": "Round 21",
    "city": "Тула",
    "date": "2021-03-08",
    "time": "14:00",
    "team1": "Арсенал",
    "team2": "Локомотив",
    "iata1": "",
    "iata2": "MOW",
    "img": "arsenal",
  },
  {
    "round": "Round 21",
    "city": "Казань",
    "date": "2021-03-06",
    "time": "",
    "team1": "Рубин",
    "team2": "Зенит",
    "iata1": "KZN",
    "iata2": "LED",
    "img": "rubin",
  },
  {
    "round": "Round 21",
    "city": "Москва",
    "date": "2021-03-06",
    "time": "",
    "team1": "Спартак",
    "team2": "Краснодар",
    "iata1": "MOW",
    "iata2": "KRR",
    "img": "spartak",
  },
  {
    "round": "Round 22",
    "city": "Тула",
    "date": "2021-03-13",
    "time": "",
    "team1": "Арсенал",
    "team2": "ЦСКА",
    "iata1": "",
    "iata2": "MOW",
    "img": "arsenal",
  },
  {
    "round": "Round 22",
    "city": "Саранск",
    "date": "2021-03-13",
    "time": "",
    "team1": "Тамбов",
    "team2": "Краснодар",
    "iata1": "SKX",
    "iata2": "KRR",
    "img": "tambov",
  },
  {
    "round": "Round 22",
    "city": "Москва",
    "date": "2021-03-12",
    "time": "19:00",
    "team1": "Химки",
    "team2": "Ростов",
    "iata1": "MOW",
    "iata2": "ROV",
    "img": "khimki",
  },
  {
    "round": "Round 23",
    "city": "Краснодар",
    "date": "2021-03-20",
    "time": "",
    "team1": "Краснодар",
    "team2": "Динамо",
    "iata1": "KRR",
    "iata2": "MOW",
    "img": "krasnodar",
  },
  {
    "round": "Round 23",
    "city": "Уфа",
    "date": "2021-03-20",
    "time": "",
    "team1": "Уфа",
    "team2": "Локомотив",
    "iata1": "UFA",
    "iata2": "MOW",
    "img": "ufa",
  },
  {
    "round": "Round 23",
    "city": "Волгоград",
    "date": "2021-03-17",
    "time": "18:00",
    "team1": "Ротор",
    "team2": "Ростов",
    "iata1": "VOG",
    "iata2": "ROV",
    "img": "rotor",
  },
  {
    "round": "Round 23",
    "city": "Москва",
    "date": "2021-03-20",
    "time": "",
    "team1": "ЦСКА",
    "team2": "Зенит",
    "iata1": "MOW",
    "iata2": "LED",
    "img": "cska",
  },
  {
    "round": "Round 24",
    "city": "Ростов на Дону",
    "date": "2021-04-03",
    "time": "",
    "team1": "Ростов",
    "team2": "Спартак",
    "iata1": "ROV",
    "iata2": "MOW",
    "img": "rostov",

  },
  {
    "round": "Round 24",
    "city": "Саранск",
    "date": "2021-04-03",
    "time": "",
    "team1": "Тамбов",
    "team2": "ЦСКА",
    "iata1": "SKX",
    "iata2": "MOW",
    "img": "tambov",
  },
  {
    "round": "Round 24",
    "city": "Волгоград",
    "date": "2021-04-03",
    "time": "",
    "team1": "Ротор",
    "team2": "Локомотив",
    "iata1": "VOG",
    "iata2": "MOW",
    "img": "rotor",
  },
  {
    "round": "Round 25",
    "city": "Тула",
    "date": "2021-04-10",
    "time": "",
    "team1": "Арсенал",
    "team2": "Краснодар",
    "iata1": "",
    "iata2": "KRR",
    "img": "arsenal",
  },
  {
    "round": "Round 25",
    "city": "Сочи",
    "date": "2021-04-10",
    "time": "",
    "team1": "Сочи",
    "team2": "Зенит",
    "iata1": "AER",
    "iata2": "LED",
    "img": "sochi",
  },
  {
    "round": "Round 26",
    "city": "Краснодар",
    "date": "2021-04-17",
    "time": "",
    "team1": "Краснодар",
    "team2": "Зенит",
    "iata1": "KRR",
    "iata2": "LED",
    "img": "krasnodar",
  },
  {
    "round": "Round 26",
    "city": "Москва",
    "date": "2021-04-17",
    "time": "18:01",
    "team1": "Локомотив",
    "team2": "Ростов",
    "iata1": "MOW",
    "iata2": "ROV",
    "img": "lokomotiv",
  },
  {
    "round": "Round 26",
    "city": "Волгоград",
    "date": "2021-04-17",
    "time": "",
    "team1": "Ротор",
    "team2": "Динамо",
    "iata1": "VOG",
    "iata2": "MOW",
    "img": "rotor",
  },
  {
    "round": "Round 26",
    "city": "Сочи",
    "date": "2021-04-17",
    "time": "",
    "team1": "Сочи",
    "team2": "ЦСКА",
    "iata1": "AER",
    "iata2": "MOW",
    "img": "sochi",
  },
  {
    "round": "Round 27",
    "city": "Саранск",
    "date": "2021-04-24",
    "time": "",
    "team1": "Тамбов",
    "team2": "Локомотив",
    "iata1": "SKX",
    "iata2": "MOW",
    "img": "tambov",
  },
  {
    "round": "Round 27",
    "city": "Казань",
    "date": "2021-04-24",
    "time": "",
    "team1": "Рубин",
    "team2": "Краснодар",
    "iata1": "KZN",
    "iata2": "KRR",
    "img": "rubin",
  },
  {
    "round": "Round 28",
    "city": "Тула",
    "date": "2021-05-01",
    "time": "",
    "team1": "Арсенал",
    "team2": "Спартак",
    "iata1": "",
    "iata2": "MOW",
    "img": "arsenal",
  },
  {
    "round": "Round 28",
    "city": "Казань",
    "date": "2021-05-01",
    "time": "",
    "team1": "Рубин",
    "team2": "Динамо",
    "iata1": "KZN",
    "iata2": "MOW",
    "img": "rubin",
  },
  {
    "round": "Round 28",
    "city": "Санкт-Петербург",
    "date": "2021-05-01",
    "time": "",
    "team1": "Зенит",
    "team2": "Локомотив",
    "iata1": "LED",
    "iata2": "MOW",
    "img": "zenit",
  },
  {
    "round": "Round 29",
    "city": "Уфа",
    "date": "2021-05-08",
    "time": "",
    "team1": "Уфа",
    "team2": "Зенит",
    "iata1": "UFA",
    "iata2": "LED",
    "img": "ufa",
  },
  {
    "round": "Round 29",
    "city": "Екатеринбург",
    "date": "2021-05-08",
    "time": "18:01",
    "team1": "Урал",
    "team2": "Ростов",
    "iata1": "SVX",
    "iata2": "ROV",
    "img": "ural",
  },
  {
    "round": "Round 29",
    "date": "2021-05-08",
    "time": "",
    "city": "Москва",
    "team1": "ЦСКА",
    "team2": "Краснодар",
    "iata1": "MOW",
    "iata2": "KRR",
    "img": "cska",
  },
  {
    "round": "Round 30",
    "city": "Ростов на Дону",
    "date": "2021-05-16",
    "time": "",
    "team1": "Ростов",
    "team2": "Краснодар",
    "iata1": "ROV",
    "iata2": "KRR",
    "img": "rostov",
  },
  {
    "round": "Round 30",
    "city": "Саранск",
    "date": "2021-05-16",
    "time": "",
    "team1": "Тамбов",
    "team2": "Зенит",
    "iata1": "SKX",
    "iata2": "LED",
    "img": "tambov",
  },
  {
    "round": "Round 30",
    "city": "Грозный",
    "date": "2021-05-16",
    "time": "",
    "team1": "Ахмат",
    "team2": "Спартак",
    "iata1": "GRV",
    "iata2": "MOW",
    "img": "akhmat",
  },
];
let daysOfWeek = ['Воскресенье',
  'Понедельник',
  'Вторник',
  'Среда',
  'Четверг',
  'Пятница',
  'Суббота',
];
